import = ["/home/_alk/.config/alacritty/themes/dracula.toml"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 17.0

[font.bold]
family = "3270 Nerd Font"
style = "Bold"

[font.bold_italic]
family = "3270 Nerd Font"
style = "Bold Italic"

[font.italic]
family = "3270 Nerd Font"
style = "Italic"

[font.normal]
family = "3270 Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\" {-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 50000

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 0.8
